name: GitHub Actions
on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v4.2.2
        with:
          ref: ''
          path: ''
      - name: download
        run: |
          curl -O https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
          cat /dev/null > ad.conf
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/224.txt
        #  curl -O https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/filters.txt
        #  curl -O https://ublockorigin.github.io/uAssetsCDN/filters/badware.min.txt
        #  curl -O https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt
        #  curl -O https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/quick-fixes.txt
        #  curl -O https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/unbreak.txt
        #  curl -O https://easylist.to/easylist/easylist.txt
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/11.txt
        #  curl -O https://curbengh.github.io/malware-filter/urlhaus-filter-ag-online.txt
      - name: Issue-conf
        run: python3 ad.py
      - name: release
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ad.conf
          git commit -m "Build daily"
          git push
          
       
