name: GitHub Actions
on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Issue-conf
        run: python ad.py
      - name: release
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Build dayily"
          git push origin main 
          
       
