name: GitHub Actions
on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: download
        run: |
          curl -O https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt
          curl -O https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt
        #  curl -O https://github.com/uBlockOrigin/uAssets/blob/master/filters/privacy.txt
        #  curl -O https://github.com/uBlockOrigin/uAssets/blob/master/filters/quick-fixes.txt
        #  curl -O https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt
        #  curl -O https://easylist.to/easylist/easylist.txt
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/11.txt
        #  curl -O https://curbengh.github.io/malware-filter/urlhaus-filter-ag-online.txt
        #  curl -O https://filters.adtidy.org/extension/ublock/filters/224.txt
        #  curl -O https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
      - name: Issue-conf
        run: python ad.py
      - name: release
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Build dayily"
          git push origin main 
          
       
