name: GitHub Actions
on:
  schedule:
    - cron: '0 0 * * 1,4'
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v4.2.2
        with:
          ref: ''
          path: ''
      - name: download
        run: |
          chmod +x Pull.sh
          ./Pull.sh
      - name: Issue-conf
        run: python3 ad.py
      - name: release
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ad.conf
          git commit -m "Build daily"
          git push -f
          
       
